name: Relat贸rio de Commits

on:
  pull_request:
    types: [closed]

jobs:
  commit_report:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch all commits
        run: git fetch --prune --unshallow

      - name: Gerar relat贸rio de commits em TXT
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.sha }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          REPORT_PATH="commit_report.txt"

          {
            echo "Relat贸rio de Commits da PR #${PR_NUMBER}";
            echo "Este relat贸rio cont茅m todos os commits associados ao PR #${PR_NUMBER}.";
            echo "------------------------------------------------------------";
            echo "Commits neste PR:";
            git log $BASE_SHA..$HEAD_SHA --oneline --pretty=format:"Commit [%h] - Autor: %an, Data: %ar, Mensagem: %s";
            echo "------------------------------------------------------------";
          } > $REPORT_PATH

          echo "Relat贸rio de Commits da PR #${PR_NUMBER}" > $REPORT_PATH
          echo "Este relat贸rio cont茅m todos os commits associados ao PR #${PR_NUMBER}." >> $REPORT_PATH
          echo "------------------------------------------------------------" >> $REPORT_PATH

          echo "Commits neste PR:" >> $REPORT_PATH
          git log $BASE_SHA..$HEAD_SHA --oneline --pretty=format:"Commit [%h] - Autor: %an, Data: %ar, Mensagem: %s" >> $REPORT_PATH
          echo "------------------------------------------------------------" >> $REPORT_PATH


      - name: Upload TXT commit report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: commit-report-txt
          path: commit_report.txt

      - name: Publicar coment谩rio com link de download
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const prNumber = ${{ github.event.pull_request.number }};
            const repoUrl = `https://github.com/${{ github.repository }}`;
            const artifactUrl = `${repoUrl}/actions/runs/${{ github.run_id }}`;
            const commentBody = `
              ###  Relat贸rio de Commits da PR #${prNumber}

              Voc锚 pode baixar o relat贸rio detalhado em TXT [aqui](${artifactUrl}).
            `;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: commentBody,
            });